// `.open-next/worker.js` is generated by @opennextjs/cloudflare during build.
import openNextWorker from "./.open-next/worker.js";

function clean(value) {
  return String(value || "").trim();
}

async function sendTelegramEvent(env, event = {}) {
  if (clean(env.TELEGRAM_HARD_DISABLE).toLowerCase() === "true") {
    return { skipped: true, reason: "hard_disabled" };
  }

  const token = clean(env.TELEGRAM_BOT_TOKEN);
  const telegram = event.telegram || {};
  const chatId = clean(telegram.chat_id || env.TELEGRAM_CHAT_ID);
  const text = clean(telegram.text);
  const photo = clean(telegram.photo);
  const document = clean(telegram.document);

  if (!token) throw new Error("TELEGRAM_BOT_TOKEN belum dikonfigurasi");
  if (!chatId) throw new Error("TELEGRAM_CHAT_ID belum dikonfigurasi");
  if (!text) throw new Error("Pesan Telegram kosong");

  let method = "sendMessage";
  let payload = {
    chat_id: chatId,
    text,
    parse_mode: telegram.parse_mode || "HTML",
    disable_web_page_preview: telegram.disable_web_page_preview !== false,
  };

  if (photo) {
    method = "sendPhoto";
    payload = {
      chat_id: chatId,
      photo,
      caption: text,
      parse_mode: telegram.parse_mode || "HTML",
    };
  } else if (document) {
    method = "sendDocument";
    payload = {
      chat_id: chatId,
      document,
      caption: text,
      parse_mode: telegram.parse_mode || "HTML",
    };
  }

  if (telegram.reply_markup) payload.reply_markup = telegram.reply_markup;
  const messageThreadId = clean(telegram.message_thread_id || env.TELEGRAM_MESSAGE_THREAD_ID);
  if (messageThreadId) {
    payload.message_thread_id = Number(messageThreadId);
  }

  const response = await fetch(`https://api.telegram.org/bot${token}/${method}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload),
  });

  const result = await response.json().catch(() => ({}));
  if (!response.ok || result.ok === false) {
    throw new Error(result.description || `Telegram API gagal (${response.status})`);
  }

  return result.result || result;
}

export default {
  fetch: openNextWorker.fetch,

  async queue(batch, env) {
    for (const message of batch.messages) {
      try {
        await sendTelegramEvent(env, message.body);
        message.ack();
      } catch (error) {
        console.error("Telegram queue delivery failed", {
          event_id: message.body?.event_id,
          type: message.body?.type,
          attempts: message.attempts,
          error: error instanceof Error ? error.message : String(error),
        });

        message.retry({
          delaySeconds: Math.min(60 * (2 ** Math.max(Number(message.attempts || 1) - 1, 0)), 900),
        });
      }
    }
  },
};
