version: '3.8'

services:
  kas-amarta:
    image: ${DOCKER_IMAGE}
    container_name: kas-amarta

    environment:
      NODE_ENV: production

    env_file:
      - .env

    restart: unless-stopped

    healthcheck:
      disable: true

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M


    networks:
      - proxy

networks:
  proxy:
    external: true
