version: '3.8'

services:
  kas-amarta:
    image: ${DOCKER_IMAGE}
    container_name: kas-amarta

    environment:
      NODE_ENV: production
      HOSTNAME: "0.0.0.0"

    env_file:
      - .env

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M


    networks:
      - proxy

networks:
  proxy:
    external: true
