export const INTEGRATION_CONFIG_DEFINITIONS = Object.freeze([
  {
    key: "APP_PLATFORM",
    group: "Application",
    category: "application",
    label: "Application Platform",
    description: "Informational platform label used by monitoring. It does not control the actual runtime.",
    type: "select",
    valueType: "string",
    options: ["cloudflare", "vercel", "netlify", "render", "local", "other"],
  },
  {
    key: "APP_URL",
    group: "Application",
    category: "application",
    label: "Canonical Application URL",
    description: "Public base URL used by Telegram webhooks, email links, and generated application links.",
    type: "url",
    valueType: "url",
  },
  {
    key: "WEBAUTH_RP_NAME",
    group: "Application",
    category: "application",
    label: "WebAuth RP Name",
    description: "Display name shown by the browser during passkey registration.",
    type: "text",
    valueType: "string",
  },
  {
    key: "WA_API_URL",
    group: "WhatsApp",
    category: "whatsapp",
    label: "WhatsApp API URL",
    description: "External WhatsApp API base URL.",
    type: "url",
    valueType: "url",
  },
  {
    key: "WA_SESSION_ID",
    group: "WhatsApp",
    category: "whatsapp",
    label: "WhatsApp Session ID",
    description: "Session used by all WhatsApp delivery flows. Changing it may require pairing again.",
    type: "text",
    valueType: "string",
  },
  {
    key: "WA_ALERT_CHAT_ID",
    group: "WhatsApp",
    category: "whatsapp",
    label: "WhatsApp Alert Chat ID",
    description: "Destination used for administrative alerts and WhatsApp test fallback.",
    type: "text",
    valueType: "string",
  },
  {
    key: "WA_REPORT_CHAT_ID",
    group: "WhatsApp",
    category: "whatsapp",
    label: "WhatsApp Report Chat ID",
    description: "Destination used for monthly summaries and payment reminders.",
    type: "text",
    valueType: "string",
  },
  {
    key: "TELEGRAM_CHAT_ID",
    group: "Telegram",
    category: "telegram",
    label: "Telegram Chat ID",
    description: "Telegram group or chat that receives alerts and approval actions.",
    type: "text",
    valueType: "string",
  },
  {
    key: "EMAIL_NOTIFICATIONS_ENABLED",
    group: "Email",
    category: "email",
    label: "Email Notifications",
    description: "Master switch for system email notifications.",
    type: "boolean",
    valueType: "boolean",
  },
  {
    key: "ALERT_EMAIL_FROM",
    group: "Email",
    category: "email",
    label: "Email Sender",
    description: "Verified sender identity accepted by the email provider.",
    type: "email",
    valueType: "string",
  },
  {
    key: "ALERT_EMAIL_TO",
    group: "Email",
    category: "email",
    label: "Email Recipients",
    description: "Comma-separated recipient email addresses.",
    type: "email-list",
    valueType: "string_array",
  },
  {
    key: "R2_BUCKET_NAME",
    group: "Storage",
    category: "storage",
    label: "R2 Bucket Name",
    description: "Cloudflare R2 bucket used for receipts, payment proofs, and activity images.",
    type: "text",
    valueType: "string",
  },
  {
    key: "R2_PUBLIC_URL",
    group: "Storage",
    category: "storage",
    label: "R2 Public URL",
    description: "Public HTTPS base URL used to access uploaded files.",
    type: "url",
    valueType: "url",
  },
  {
    key: "CLOUDFLARE_QUEUE_PUSH_URL",
    group: "Queue",
    category: "queue",
    label: "Cloudflare Queue Push URL",
    description: "HTTP endpoint used by the application to publish Telegram events to Cloudflare Queue.",
    type: "url",
    valueType: "url",
  },
]);

export const INTEGRATION_CONFIG_DEFINITION_MAP = Object.freeze(
  Object.fromEntries(INTEGRATION_CONFIG_DEFINITIONS.map((item) => [item.key, item])),
);

export const INTEGRATION_CONFIG_GROUPS = Object.freeze([
  "Application",
  "WhatsApp",
  "Telegram",
  "Email",
  "Storage",
  "Queue",
]);
