"use client";

import Toast from "@/components/Toast";
import AdminConfirmModal from "@/components/admin/AdminConfirmModal";
import { readJson, sendJson } from "@/components/admin/adminClientApi";
import { useEffect, useMemo, useRef, useState } from "react";

const API = "/api/admin/approval-requests";
const SIZE = 10;
const DONE = ["completed", "rejected", "cancelled"];
const CSS = `.ac-toolbar{display:grid;gap:10px;margin:14px 0}.ac-list{display:grid;gap:12px}.ac-card{display:grid;gap:12px;padding:12px;border:1px solid var(--admin-border);border-radius:16px;background:var(--admin-card)}.ac-head{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px}.ac-no{font-size:17px;font-weight:900;overflow-wrap:anywhere}.ac-type{margin-top:4px;color:var(--admin-muted);font-size:14px;font-weight:700}.ac-status{font-size:13px;font-weight:900;line-height:1.2;text-align:right;white-space:nowrap}.ac-ok{color:#15803d}.ac-wait{color:#92400e}.ac-bad{color:#991b1b}.ac-muted-status{color:var(--admin-muted)}.ac-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.ac-field{padding:9px 10px;border:1px solid var(--admin-border);border-radius:12px;background:var(--admin-row);min-width:0}.ac-label{display:block;margin-bottom:4px;color:var(--admin-muted);font-size:10px;font-weight:900;letter-spacing:.06em;text-transform:uppercase}.ac-value{display:block;font-size:13px;font-weight:800;line-height:1.3;overflow-wrap:anywhere}.ac-muted{display:block;margin-top:3px;color:var(--admin-muted);font-size:12px;font-weight:700}.ac-steps{display:flex;gap:10px;flex-wrap:wrap}.ac-step{font-size:12px;font-weight:900}.ac-step small{display:block;color:var(--admin-muted);font-size:10px;font-weight:900;text-transform:uppercase}.ac-step-ok{color:#15803d}.ac-step-wait{color:#92400e}.ac-step-full{color:#15803d}.ac-notes{display:grid;gap:7px;padding:10px;border:1px dashed var(--admin-border);border-radius:12px;background:var(--admin-row)}.ac-note-row{font-size:12px;line-height:1.35}.ac-note-row small{display:block;color:var(--admin-muted);font-size:10px;font-weight:900;text-transform:uppercase}.ac-note-text{margin-top:2px;font-weight:700;overflow-wrap:anywhere}.ac-actions{display:flex;gap:8px;flex-wrap:wrap}.ac-actions .admin-small-btn{flex:1 1 120px;min-height:42px;border-radius:12px}.ac-reject{background:#fee2e2!important;color:#991b1b!important;border:1px solid #fca5a5!important}.ac-note{width:100%;min-height:86px;box-sizing:border-box;padding:12px;border:1px solid var(--admin-border);border-radius:12px;background:var(--admin-input);color:var(--admin-text);font:inherit}.ac-meta,.ac-loader{color:var(--admin-muted);font-size:12px;font-weight:800}.ac-loader{text-align:center;padding:14px 0 4px}@media(max-width:640px){.ac-title{font-size:28px!important}.ac-summary{grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:8px!important}.ac-section{padding:14px!important;border-radius:16px!important}.ac-status{text-align:left}}`;

function roleKey(v){return String(v||"").trim().toLowerCase()}
function date(v){const d=new Date(v);return v&&!Number.isNaN(d.getTime())?d.toLocaleString("id-ID",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}):"-"}
function rupiah(v){return `Rp${Number(v||0).toLocaleString("id-ID")}`}
function done(v){return DONE.includes(roleKey(v))}
function actionable(r,role="admin"){const current=roleKey(r?.current_approver_role);const access=roleKey(role)||"admin";return !!r&&!done(r.status)&&!!current&&(access==="admin"||current===access)}
function meta(s){const v=roleKey(s);if(v==="completed")return["Full Approved","ac-ok"];if(v==="rejected")return["Rejected","ac-bad"];if(v==="cancelled")return["Cancelled","ac-bad"];if(v==="waiting_payment_validation")return["Waiting for Validation","ac-wait"];if(v==="waiting_approval")return["Waiting for Approval","ac-wait"];return[v||"-","ac-muted-status"]}
function actionLabel(a){const v=roleKey(a?.action);if(v==="reject")return"Rejected";if(v==="validate_payment")return"Validated";if(v==="approve"||v==="final_approval")return"Approved";if(v==="submit")return"Submitted";return v||"Action"}
function haystack(r){return [r.request_no,r.master_name,r.requester_name,r.requester_house,r.current_approver_role,r.status,r.amount,(r.approval_actions||[]).map(a=>`${a.role} ${a.action} ${a.note||""}`).join(" ")].join(" ").toLowerCase()}
function Status({status}){const [label,cls]=meta(status);return <span className={`ac-status ${cls}`}>{label}</span>}
function Field({label,value,muted}){return <div className="ac-field"><span className="ac-label">{label}</span><span className="ac-value">{value||"-"}</span>{muted?<span className="ac-muted">{muted}</span>:null}</div>}
function Summary({label,value,active,onClick}){return <button type="button" className={active?"admin-summary-card admin-summary-card-active":"admin-summary-card"} style={{cursor:"pointer",border:"1px solid var(--admin-border)"}} onClick={onClick}><div className="admin-status-label">{label}</div><div className="admin-status-value" style={{marginBottom:0}}>{value}</div></button>}
function Steps({row}){const actions=(row.approval_actions||[]).filter(a=>!["submit","reject"].includes(roleKey(a.action)));const approved=[...new Map(actions.map(a=>[a.role,a])).values()];if(row.status==="completed")return <div className="ac-steps"><div className="ac-step ac-step-full"><small>Status</small><span>Full Approved</span></div>{approved.map(a=><div key={a.id||a.role} className="ac-step ac-step-ok"><small>{a.role}</small><span>Approved</span></div>)}</div>;return <div className="ac-steps">{approved.map(a=><div key={a.id||a.role} className="ac-step ac-step-ok"><small>{a.role}</small><span>Approved</span></div>)}{row.current_approver_role&&!done(row.status)?<div className="ac-step ac-step-wait"><small>{row.current_approver_role}</small><span>Waiting for Approval</span></div>:null}</div>}
function Notes({row}){const notes=(row.approval_actions||[]).filter(a=>String(a.note||"").trim());if(!notes.length)return null;return <div className="ac-notes"><span className="ac-label">Approval Notes</span>{notes.map(a=><div key={a.id||`${a.role}-${a.created_at}`} className="ac-note-row"><small>{a.role||"-"} · {actionLabel(a)} · {date(a.created_at)}</small><div className="ac-note-text">{a.note}</div></div>)}</div>}

function Cards({rows,inboxIds,runningId,onAction}){
 if(!rows.length)return <div className="admin-empty-state" style={{padding:"14px 12px"}}>No approval requests found.</div>;
 return <div className="ac-list">{rows.map(row=>{const act=row.status==="waiting_payment_validation"?"validate_payment":"approve";const label=row.status==="waiting_payment_validation"?"Validate":"Approve";const can=inboxIds.has(row.id);return <article className="ac-card" key={row.id}><div className="ac-head"><div><div className="ac-no">{row.request_no}</div><div className="ac-type">{row.master_name||"-"}</div></div><Status status={row.status}/></div><Steps row={row}/><Notes row={row}/><div className="ac-grid"><Field label="Requester" value={row.requester_name} muted={row.requester_house}/><Field label="Current Approver" value={row.current_approver_role||"-"}/><Field label="Amount" value={row.amount?rupiah(row.amount):"-"}/><Field label="Submitted At" value={date(row.created_at)}/></div>{can?<div className="ac-actions"><button className="admin-small-btn" disabled={!!runningId} onClick={()=>onAction(row,act)}>{runningId===`${row.id}-${act}`?"Processing...":label}</button><button className="admin-small-btn ac-reject" disabled={!!runningId} onClick={()=>onAction(row,"reject")}>{runningId===`${row.id}-reject`?"Processing...":"Reject"}</button></div>:null}</article>})}</div>
}

export default function ApprovalCenterTab(){
 const [data,setData]=useState({summary:{},inbox:[],requests:[]});const [loading,setLoading]=useState(true);const [runningId,setRunningId]=useState("");const [toast,setToast]=useState(null);const [pending,setPending]=useState(null);const [note,setNote]=useState("");const [filter,setFilter]=useState("all");const [search,setSearch]=useState("");const [limit,setLimit]=useState(SIZE);const loader=useRef(null);
 const accessRole=roleKey(data.access_role)||"admin";
 const all=useMemo(()=>{const m=new Map();[...(data.inbox||[]),...(data.requests||[])].forEach(r=>{if(r?.id)m.set(r.id,r)});return[...m.values()]},[data]);
 const safeInbox=useMemo(()=>all.filter(r=>actionable(r,accessRole)),[all,accessRole]);
 const inboxIds=useMemo(()=>new Set(safeInbox.map(r=>r.id)),[safeInbox]);
 const summary=useMemo(()=>({inbox:safeInbox.length,processing:all.filter(r=>!done(r.status)).length,completed:all.filter(r=>r.status==="completed").length,rejected:all.filter(r=>r.status==="rejected").length}),[all,safeInbox]);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return all.filter(r=>{const s=roleKey(r.status);const ok=filter==="all"||(filter==="inbox"&&inboxIds.has(r.id))||(filter==="processing"&&!done(s))||s===filter;return ok&&(!q||haystack(r).includes(q))})},[all,filter,search,inboxIds]);
 const shown=filtered.slice(0,limit);const more=limit<filtered.length;
 const show=(message,type="success")=>{setToast({message,type});setTimeout(()=>setToast(null),2500)};
 const chooseFilter=(key)=>setFilter(prev=>prev===key?"all":key);
 async function load(){try{setLoading(true);setData(await readJson(API))}catch(e){show(e.message||"Failed to load Approval Center","error")}finally{setLoading(false)}}
 function open(row,action){setPending({row,action});setNote("")}
 function close(){if(runningId)return;setPending(null);setNote("")}
 async function confirm(){if(!pending)return;const {row,action}=pending;const clean=note.trim();if(action==="reject"&&!clean)return show("Rejection note is required","error");try{setRunningId(`${row.id}-${action}`);await sendJson(API,"PATCH",{id:row.id,action,note:clean});show(action==="reject"?"Request rejected":"Request processed");setPending(null);setNote("");await load()}catch(e){show(e.message||"Failed to process approval request","error")}finally{setRunningId("")}}
 useEffect(()=>{load()},[]);useEffect(()=>setLimit(SIZE),[filter,search,data]);useEffect(()=>{const n=loader.current;if(!n||!more)return;const o=new IntersectionObserver(e=>{if(e[0]?.isIntersecting)setLimit(v=>Math.min(v+SIZE,filtered.length))},{rootMargin:"120px"});o.observe(n);return()=>o.disconnect()},[more,filtered.length]);
 if(loading)return <div className="admin-card">Loading Approval Center...</div>;
 const reject=pending?.action==="reject";const row=pending?.row;
 return <><Toast show={!!toast} type={toast?.type} message={toast?.message}/><style jsx global>{CSS}</style><AdminConfirmModal open={!!pending} title={reject?"Reject Request":"Confirm Approval"} description={row?`${row.request_no} - ${row.master_name||"Approval Request"}`:""} confirmText={reject?"Reject":"Process"} cancelText="Cancel" loading={!!runningId} loadingText="Processing..." onCancel={close} onConfirm={confirm}><div><div><strong>Status</strong><p>{row?meta(row.status)[0]:"-"}</p></div><div><strong>Requester</strong><p>{row?.requester_name||"-"} · {row?.requester_house||"-"}</p></div><div><strong>{reject?"Rejection Note":"Approval Note"}</strong><textarea className="ac-note" value={note} onChange={e=>setNote(e.target.value)} placeholder={reject?"Required rejection reason":"Optional"}/></div></div></AdminConfirmModal><div className="admin-card" style={{height:"auto",overflow:"visible"}}><div className="activity-header" style={{marginBottom:14}}><div><div className="activity-kicker">Approval Workflow</div><h3 className="activity-title ac-title">Approval Center</h3><p className="activity-subtitle">Click a summary card to filter. Click the active card again to show all approval requests.</p></div></div><div className="admin-summary-cards ac-summary" style={{marginBottom:0}}><Summary label="Need Action" value={summary.inbox} active={filter==="inbox"} onClick={()=>chooseFilter("inbox")}/><Summary label="In Progress" value={summary.processing} active={filter==="processing"} onClick={()=>chooseFilter("processing")}/><Summary label="Full Approved" value={summary.completed} active={filter==="completed"} onClick={()=>chooseFilter("completed")}/><Summary label="Rejected" value={summary.rejected} active={filter==="rejected"} onClick={()=>chooseFilter("rejected")}/></div><div className="ac-toolbar"><input className="admin-search-input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search request no, type, requester, house, approver, note..."/></div><section className="admin-status-card ac-section" style={{margin:0}}><div className="ac-meta">{shown.length} / {filtered.length} loaded</div><Cards rows={shown} inboxIds={inboxIds} runningId={runningId} onAction={open}/><div ref={loader} className="ac-loader">{more?"Scroll to load more":"All approval requests loaded"}</div></section></div></>
}
