"use client";

import Toast from "@/components/Toast";
import AdminConfirmModal from "@/components/admin/AdminConfirmModal";
import { readJson, sendJson } from "@/components/admin/adminClientApi";
import { useEffect, useMemo, useRef, useState } from "react";

const API = "/api/admin/approval-requests";
const SIZE = 10;
const DONE = ["completed", "rejected", "cancelled"];
const CSS = `.ac-toolbar{display:grid;gap:10px;margin:14px 0}.ac-list{display:grid;gap:12px}.ac-card{display:grid;gap:12px;padding:12px;border:1px solid var(--admin-border);border-radius:16px;background:var(--admin-card)}.ac-head{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px}.ac-no{font-size:17px;font-weight:900;overflow-wrap:anywhere}.ac-type{margin-top:4px;color:var(--admin-muted);font-size:14px;font-weight:700}.ac-status{font-size:13px;font-weight:900;line-height:1.2;text-align:right;white-space:nowrap}.ac-ok{color:#15803d}.ac-wait{color:#92400e}.ac-bad{color:#991b1b}.ac-muted-status{color:var(--admin-muted)}.ac-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.ac-field{padding:9px 10px;border:1px solid var(--admin-border);border-radius:12px;background:var(--admin-row);min-width:0}.ac-label{display:block;margin-bottom:4px;color:var(--admin-muted);font-size:10px;font-weight:900;letter-spacing:.06em;text-transform:uppercase}.ac-value{display:block;font-size:13px;font-weight:800;line-height:1.3;overflow-wrap:anywhere}.ac-muted{display:block;margin-top:3px;color:var(--admin-muted);font-size:12px;font-weight:700}.ac-steps{display:flex;gap:10px;flex-wrap:wrap}.ac-step{font-size:12px;font-weight:900}.ac-step small{display:block;color:var(--admin-muted);font-size:10px;font-weight:900;text-transform:uppercase}.ac-step-ok{color:#15803d}.ac-step-wait{color:#92400e}.ac-step-full{color:#15803d}.ac-actions{display:flex;gap:8px;flex-wrap:wrap}.ac-actions .admin-small-btn{flex:1 1 120px;min-height:42px;border-radius:12px}.ac-reject{background:#fee2e2!important;color:#991b1b!important;border:1px solid #fca5a5!important}.ac-note{width:100%;min-height:86px;box-sizing:border-box;padding:12px;border:1px solid var(--admin-border);border-radius:12px;background:var(--admin-input);color:var(--admin-text);font:inherit}.ac-meta,.ac-loader{color:var(--admin-muted);font-size:12px;font-weight:800}.ac-loader{text-align:center;padding:14px 0 4px}@media(max-width:640px){.ac-title{font-size:28px!important}.ac-summary{grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:8px!important}.ac-section{padding:14px!important;border-radius:16px!important}.ac-status{text-align:left}}`;

function date(v){const d=new Date(v);return v&&!Number.isNaN(d.getTime())?d.toLocaleString("id-ID",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}):"-"}
function rupiah(v){return `Rp${Number(v||0).toLocaleString("id-ID")}`}
function done(v){return DONE.includes(String(v||"").toLowerCase())}
function meta(s){const v=String(s||"").toLowerCase();if(v==="completed")return["Full Approved","ac-ok"];if(v==="rejected")return["Ditolak","ac-bad"];if(v==="cancelled")return["Dibatalkan","ac-bad"];if(v==="waiting_payment_validation")return["Menunggu Validasi","ac-wait"];if(v==="waiting_approval")return["Waiting for Approve","ac-wait"];return[v||"-","ac-muted-status"]}
function haystack(r){return [r.request_no,r.master_name,r.requester_name,r.requester_house,r.current_approver_role,r.status,r.amount,(r.approval_actions||[]).map(a=>`${a.role} ${a.action}`).join(" ")].join(" ").toLowerCase()}
function Status({status}){const [label,cls]=meta(status);return <span className={`ac-status ${cls}`}>{label}</span>}
function Field({label,value,muted}){return <div className="ac-field"><span className="ac-label">{label}</span><span className="ac-value">{value||"-"}</span>{muted?<span className="ac-muted">{muted}</span>:null}</div>}
function Summary({label,value,active,onClick}){return <button type="button" className={active?"admin-summary-card admin-summary-card-active":"admin-summary-card"} style={{cursor:"pointer",border:"1px solid var(--admin-border)"}} onClick={onClick}><div className="admin-status-label">{label}</div><div className="admin-status-value" style={{marginBottom:0}}>{value}</div></button>}
function Steps({row}){const actions=(row.approval_actions||[]).filter(a=>!["submit","reject"].includes(String(a.action||"").toLowerCase()));const approved=[...new Map(actions.map(a=>[a.role,a])).values()];if(row.status==="completed")return <div className="ac-steps"><div className="ac-step ac-step-full"><small>Status</small><span>Full Approved</span></div>{approved.map(a=><div key={a.id||a.role} className="ac-step ac-step-ok"><small>{a.role}</small><span>Approved</span></div>)}</div>;return <div className="ac-steps">{approved.map(a=><div key={a.id||a.role} className="ac-step ac-step-ok"><small>{a.role}</small><span>Approved</span></div>)}{row.current_approver_role&&!done(row.status)?<div className="ac-step ac-step-wait"><small>{row.current_approver_role}</small><span>Waiting for Approve</span></div>:null}</div>}

function Cards({rows,inboxIds,runningId,onAction}){
 if(!rows.length)return <div className="admin-empty-state" style={{padding:"14px 12px"}}>Pengajuan tidak ditemukan.</div>;
 return <div className="ac-list">{rows.map(row=>{const act=row.status==="waiting_payment_validation"?"validate_payment":"approve";const label=row.status==="waiting_payment_validation"?"Validasi Pembayaran":"Approve";const can=inboxIds.has(row.id)&&!done(row.status);return <article className="ac-card" key={row.id}><div className="ac-head"><div><div className="ac-no">{row.request_no}</div><div className="ac-type">{row.master_name||"-"}</div></div><Status status={row.status}/></div><Steps row={row}/><div className="ac-grid"><Field label="Pemohon" value={row.requester_name} muted={row.requester_house}/><Field label="Approver Sekarang" value={row.current_approver_role||"-"}/><Field label="Nominal" value={row.amount?rupiah(row.amount):"-"}/><Field label="Tanggal" value={date(row.created_at)}/></div>{can?<div className="ac-actions"><button className="admin-small-btn" disabled={!!runningId} onClick={()=>onAction(row,act)}>{runningId===`${row.id}-${act}`?"Processing...":label}</button><button className="admin-small-btn ac-reject" disabled={!!runningId} onClick={()=>onAction(row,"reject")}>{runningId===`${row.id}-reject`?"Processing...":"Reject"}</button></div>:null}</article>})}</div>
}

export default function ApprovalCenterTab(){
 const [data,setData]=useState({summary:{},inbox:[],requests:[]});const [loading,setLoading]=useState(true);const [runningId,setRunningId]=useState("");const [toast,setToast]=useState(null);const [pending,setPending]=useState(null);const [note,setNote]=useState("");const [filter,setFilter]=useState("all");const [search,setSearch]=useState("");const [limit,setLimit]=useState(SIZE);const loader=useRef(null);
 const inboxIds=useMemo(()=>new Set((data.inbox||[]).map(r=>r.id)),[data.inbox]);
 const all=useMemo(()=>{const m=new Map();[...(data.inbox||[]),...(data.requests||[])].forEach(r=>m.set(r.id,r));return[...m.values()]},[data]);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return all.filter(r=>{const s=String(r.status||"").toLowerCase();const ok=filter==="all"||(filter==="inbox"&&inboxIds.has(r.id))||(filter==="processing"&&!done(s))||s===filter;return ok&&(!q||haystack(r).includes(q))})},[all,filter,search,inboxIds]);
 const shown=filtered.slice(0,limit);const more=limit<filtered.length;
 const show=(message,type="success")=>{setToast({message,type});setTimeout(()=>setToast(null),2500)};
 const chooseFilter=(key)=>setFilter(prev=>prev===key?"all":key);
 async function load(){try{setLoading(true);setData(await readJson(API))}catch(e){show(e.message||"Gagal membaca Approval Center","error")}finally{setLoading(false)}}
 function open(row,action){setPending({row,action});setNote("")}
 function close(){if(runningId)return;setPending(null);setNote("")}
 async function confirm(){if(!pending)return;const {row,action}=pending;const clean=note.trim();if(action==="reject"&&!clean)return show("Catatan penolakan wajib diisi","error");try{setRunningId(`${row.id}-${action}`);await sendJson(API,"PATCH",{id:row.id,action,note:clean});show(action==="reject"?"Pengajuan ditolak":"Pengajuan diproses");setPending(null);setNote("");await load()}catch(e){show(e.message||"Gagal memproses approval","error")}finally{setRunningId("")}}
 useEffect(()=>{load()},[]);useEffect(()=>setLimit(SIZE),[filter,search,data]);useEffect(()=>{const n=loader.current;if(!n||!more)return;const o=new IntersectionObserver(e=>{if(e[0]?.isIntersecting)setLimit(v=>Math.min(v+SIZE,filtered.length))},{rootMargin:"120px"});o.observe(n);return()=>o.disconnect()},[more,filtered.length]);
 if(loading)return <div className="admin-card">Loading Approval Center...</div>;
 const reject=pending?.action==="reject";const row=pending?.row;
 return <><Toast show={!!toast} type={toast?.type} message={toast?.message}/><style jsx global>{CSS}</style><AdminConfirmModal open={!!pending} title={reject?"Tolak Pengajuan":"Konfirmasi Approval"} description={row?`${row.request_no} - ${row.master_name||"Pengajuan"}`:""} confirmText={reject?"Reject":"Proses"} cancelText="Batal" loading={!!runningId} loadingText="Processing..." onCancel={close} onConfirm={confirm}><div><div><strong>Status</strong><p>{row?meta(row.status)[0]:"-"}</p></div><div><strong>Pemohon</strong><p>{row?.requester_name||"-"} · {row?.requester_house||"-"}</p></div><div><strong>Catatan {reject?"Penolakan":"Approval"}</strong><textarea className="ac-note" value={note} onChange={e=>setNote(e.target.value)} placeholder={reject?"Wajib isi alasan penolakan":"Opsional"}/></div></div></AdminConfirmModal><div className="admin-card" style={{height:"auto",overflow:"visible"}}><div className="activity-header" style={{marginBottom:14}}><div><div className="activity-kicker">Approval Workflow</div><h3 className="activity-title ac-title">Approval Center</h3><p className="activity-subtitle">Klik summary card untuk filter. Klik ulang card aktif untuk kembali menampilkan semua pengajuan.</p></div></div><div className="admin-summary-cards ac-summary" style={{marginBottom:0}}><Summary label="Inbox Saya" value={data.summary?.inbox||0} active={filter==="inbox"} onClick={()=>chooseFilter("inbox")}/><Summary label="Sedang Proses" value={data.summary?.processing||0} active={filter==="processing"} onClick={()=>chooseFilter("processing")}/><Summary label="Selesai" value={data.summary?.completed||0} active={filter==="completed"} onClick={()=>chooseFilter("completed")}/><Summary label="Ditolak" value={data.summary?.rejected||0} active={filter==="rejected"} onClick={()=>chooseFilter("rejected")}/></div><div className="ac-toolbar"><input className="admin-search-input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari no, jenis, pemohon, rumah, approver..."/></div><section className="admin-status-card ac-section" style={{margin:0}}><div className="ac-meta">{shown.length} / {filtered.length} loaded</div><Cards rows={shown} inboxIds={inboxIds} runningId={runningId} onAction={open}/><div ref={loader} className="ac-loader">{more?"Scroll to load more":"All approval requests loaded"}</div></section></div></>
}
