"use client";

import Toast from "@/components/Toast";
import AdminConfirmModal from "@/components/admin/AdminConfirmModal";
import { readJson, sendJson } from "@/components/admin/adminClientApi";
import { useEffect, useMemo, useState } from "react";

const API = "/api/admin/approval-requests";
const DONE = ["completed", "rejected", "cancelled"];
const css = `
.approval-list{display:grid;gap:12px}.approval-card{display:grid;gap:12px;padding:12px;border:1px solid var(--admin-border);border-radius:16px;background:var(--admin-card)}
.approval-head{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:start}.approval-no{font-size:17px;font-weight:900;overflow-wrap:anywhere}.approval-type{margin-top:4px;color:var(--admin-muted);font-size:14px;font-weight:700;overflow-wrap:anywhere}
.approval-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.approval-field{padding:9px 10px;border:1px solid var(--admin-border);border-radius:12px;background:var(--admin-row);min-width:0}.approval-label{display:block;margin-bottom:4px;color:var(--admin-muted);font-size:10px;font-weight:900;letter-spacing:.06em;text-transform:uppercase}.approval-value{display:block;font-size:13px;font-weight:800;line-height:1.3;overflow-wrap:anywhere}.approval-muted{display:block;margin-top:3px;color:var(--admin-muted);font-size:12px;font-weight:700;overflow-wrap:anywhere}
.approval-actions{display:flex;gap:8px;flex-wrap:wrap}.approval-actions .admin-small-btn{flex:1 1 120px;min-height:42px;border-radius:12px}.approval-reject{background:#fee2e2!important;color:#991b1b!important;border:1px solid #fca5a5!important}.approval-note{width:100%;min-height:86px;box-sizing:border-box;padding:12px;border:1px solid var(--admin-border);border-radius:12px;background:var(--admin-input);color:var(--admin-text);font:inherit}
@media(max-width:640px){.approval-title{font-size:28px!important}.approval-summary{grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:8px!important}.approval-summary .admin-summary-card{min-height:72px;display:grid;place-items:center}.approval-section{padding:14px!important;border-radius:16px!important}}
`;

function fmtDate(v){const d=new Date(v);return v&&!Number.isNaN(d.getTime())?d.toLocaleString("id-ID",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}):"-"}
function money(v){return `Rp${Number(v||0).toLocaleString("id-ID")}`}
function meta(s){const v=String(s||"").toLowerCase();if(v==="completed")return["Selesai","admin-deposit-status-paid"];if(v==="rejected")return["Ditolak","admin-deposit-status-missed"];if(v==="cancelled")return["Dibatalkan","admin-deposit-status-missed"];if(v==="waiting_payment_validation")return["Menunggu Validasi","admin-deposit-status-pending"];if(v==="waiting_approval")return["Menunggu Approval","admin-deposit-status-pending"];return[v||"-","admin-deposit-status-waiting"]}
function Badge({status}){const [label,cls]=meta(status);return <span className={`admin-deposit-status ${cls}`}>{label}</span>}
function Field({label,value,muted}){return <div className="approval-field"><span className="approval-label">{label}</span><span className="approval-value">{value||"-"}</span>{muted?<span className="approval-muted">{muted}</span>:null}</div>}
function Summary({label,value}){return <div className="admin-summary-card" style={{cursor:"default"}}><div className="admin-status-label">{label}</div><div className="admin-status-value" style={{marginBottom:0}}>{value}</div></div>}
function Section({title,description,children}){return <section className="admin-status-card approval-section" style={{margin:0,height:"auto",overflow:"visible"}}><div className="admin-status-label" style={{textAlign:"left"}}>{title}</div><div className="admin-status-meta" style={{marginBottom:10}}>{description}</div>{children}</section>}

function Requests({rows,runningId,onAction,showActions=false}){
 if(!rows.length)return <div className="admin-empty-state" style={{padding:"14px 12px"}}>Tidak ada pengajuan.</div>;
 return <div className="approval-list">{rows.map(row=>{const done=DONE.includes(String(row.status||"").toLowerCase());const action=row.status==="waiting_payment_validation"?"validate_payment":"approve";const label=row.status==="waiting_payment_validation"?"Validasi Pembayaran":"Approve";return <article className="approval-card" key={row.id}><div className="approval-head"><div><div className="approval-no">{row.request_no}</div><div className="approval-type">{row.master_name||"-"}</div></div><Badge status={row.status}/></div><div className="approval-grid"><Field label="Pemohon" value={row.requester_name} muted={row.requester_house}/><Field label="Approver" value={row.current_approver_role}/><Field label="Nominal" value={row.amount?money(row.amount):"-"}/><Field label="Tanggal" value={fmtDate(row.created_at)}/></div>{showActions&&!done?<div className="approval-actions"><button className="admin-small-btn" disabled={!!runningId} onClick={()=>onAction(row,action)}>{runningId===`${row.id}-${action}`?"Processing...":label}</button><button className="admin-small-btn approval-reject" disabled={!!runningId} onClick={()=>onAction(row,"reject")}>{runningId===`${row.id}-reject`?"Processing...":"Reject"}</button></div>:null}</article>})}</div>
}

export default function ApprovalCenterTab(){
 const [data,setData]=useState({summary:{},inbox:[],requests:[]});const [loading,setLoading]=useState(true);const [runningId,setRunningId]=useState("");const [toast,setToast]=useState(null);const [pending,setPending]=useState(null);const [note,setNote]=useState("");
 const visible=useMemo(()=>{const ids=new Set((data.inbox||[]).map(r=>r.id));return(data.requests||[]).filter(r=>!ids.has(r.id))},[data]);
 const show=(message,type="success")=>{setToast({message,type});setTimeout(()=>setToast(null),2500)};
 async function load(){try{setLoading(true);setData(await readJson(API))}catch(e){show(e.message||"Gagal membaca Approval Center","error")}finally{setLoading(false)}}
 function open(row,action){setPending({row,action});setNote("")}
 function close(){if(runningId)return;setPending(null);setNote("")}
 async function confirm(){if(!pending)return;const {row,action}=pending;const clean=note.trim();if(action==="reject"&&!clean)return show("Catatan penolakan wajib diisi","error");try{setRunningId(`${row.id}-${action}`);await sendJson(API,"PATCH",{id:row.id,action,note:clean});show(action==="reject"?"Pengajuan ditolak":"Pengajuan diproses");setPending(null);setNote("");await load()}catch(e){show(e.message||"Gagal memproses approval","error")}finally{setRunningId("")}}
 useEffect(()=>{load()},[]);if(loading)return <div className="admin-card">Loading Approval Center...</div>;
 const isReject=pending?.action==="reject";const row=pending?.row;
 return <><Toast show={!!toast} type={toast?.type} message={toast?.message}/><style jsx global>{css}</style><AdminConfirmModal open={!!pending} title={isReject?"Tolak Pengajuan":"Konfirmasi Approval"} description={row?`${row.request_no} - ${row.master_name||"Pengajuan"}`:""} confirmText={isReject?"Reject":"Proses"} cancelText="Batal" loading={!!runningId} loadingText="Processing..." onCancel={close} onConfirm={confirm}><div><div><strong>Status</strong><p>{row?meta(row.status)[0]:"-"}</p></div><div><strong>Pemohon</strong><p>{row?.requester_name||"-"} · {row?.requester_house||"-"}</p></div><div><strong>Catatan {isReject?"Penolakan":"Approval"}</strong><textarea className="approval-note" value={note} onChange={e=>setNote(e.target.value)} placeholder={isReject?"Wajib isi alasan penolakan":"Opsional"}/></div></div></AdminConfirmModal><div className="admin-card" style={{height:"auto",overflow:"visible"}}><div className="activity-header" style={{marginBottom:14}}><div><div className="activity-kicker">Approval Workflow</div><h3 className="activity-title approval-title">Approval Center</h3><p className="activity-subtitle">Inbox pengurus untuk validasi pembayaran, approve, reject, dan monitoring pengajuan warga.</p></div></div><div className="admin-summary-cards approval-summary" style={{marginBottom:0}}><Summary label="Inbox Saya" value={data.summary?.inbox||0}/><Summary label="Sedang Proses" value={data.summary?.processing||0}/><Summary label="Selesai" value={data.summary?.completed||0}/><Summary label="Ditolak" value={data.summary?.rejected||0}/></div><div style={{display:"grid",gap:12,marginTop:14}}><Section title="Inbox Saya" description="Pengajuan yang sedang menunggu role kamu."><Requests rows={data.inbox||[]} runningId={runningId} onAction={open} showActions/></Section>{visible.length?<Section title="Pengajuan Terbaru" description="Daftar pengajuan terbaru untuk monitoring."><Requests rows={visible} runningId={runningId} onAction={open}/></Section>:null}</div></div></>
}
